FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine
#FROM alpine:latest
#RUN apk update && apk add libstdc++ && apk add libintl
COPY bin/Release/netcoreapp3.1/linux-musl-x64/publish/ /root/
ENTRYPOINT /root/dotnet-test